userName=admin
password=test123
userName2=admin1
password2=test456

browser=chrome
#browser=firefox
invalidUser=Sharia
invalidPass=1234
loginError=Invalid username or password!
loginPageTitle = Login - zSolution
homePageTitle=zSolution


# ----------- URL-----------#
#url=file:///Users/khosruzzaman/ALL_JAVA/FrameWork/ZSolutionAutomationProject/WebSite/mytest.html
#url=file:///Users/khosruzzaman/ALL_JAVA/FrameWork/ZSolutionAutomationProject/zSolutions3/login.html  
#url =http://192.168.0.19:5500/login.html
#url=file:///Users/khosruzzaman/ALL_JAVA/FrameWork/ZSolutionAutomationProject/zSolutions/login.html  
#url=file:///Users/khosruzzaman/ALL_JAVA/FrameWork/ZSolutionAutomationProject/zSolutions/Kol.html  
url=file:///Users/khosruzzaman/ALL_JAVA/FrameWork/ZSolutionAutomationProject/zSolutions/login.html 